CREATE SCHEMA IF NOT EXISTS PRACTICA_FINAL_NUEVA.STAGING;
USE SCHEMA PRACTICA_FINAL_NUEVA.STAGING;

CREATE OR REPLACE TABLE STAGING.STG_ORDERS AS 
SELECT 
    O_ORDERKEY ,
    O_CUSTKEY ,
    O_ORDERSTATUS ,
    O_TOTALPRICE,
    O_ORDERDATE,
    O_ORDERPRIORITY,
    REGEXP_SUBSTR(O_CLERK, '[0-9]+'):: INT AS ID_CLERK,
    O_SHIPPRIORITY,
    O_COMMENT,
    ID_TIENDA
FROM RAW.ORDERS;



