USE SCHEMA PRACTICA_FINAL_NUEVA.STAGING;


CREATE OR REPLACE TABLE STAGING.STG_LINEITEM CLONE RAW.LINEITEM;

CREATE OR REPLACE TABLE STAGING.STG_CUSTOMER CLONE RAW.CUSTOMER;

CREATE OR REPLACE TABLE STAGING.STG_PART CLONE RAW.PART;

CREATE OR REPLACE TABLE STAGING.STG_PARTSUPP CLONE RAW.PARTSUPP;

CREATE OR REPLACE TABLE STAGING.STG_SUPPLIER CLONE RAW.SUPPLIER;

CREATE OR REPLACE TABLE STAGING.STG_NATION CLONE RAW.NATION;

CREATE OR REPLACE TABLE STAGING.STG_REGION CLONE RAW.REGION;

CREATE OR REPLACE TABLE STAGING.STG_TIENDA CLONE RAW.TIENDA;

CREATE OR REPLACE TABLE STAGING.STG_PROMOCION CLONE RAW.PROMOCION;

CREATE OR REPLACE TABLE STAGING.STG_PROMOCION_PAIS CLONE RAW.PROMOCION_PAIS;

CREATE OR REPLACE TABLE STAGING.STG_CAMBIO CLONE RAW.CAMBIO;

SELECT * FROM STG_LINEITEM;