USE SCHEMA PRACTICA_FINAL_NUEVA.RAW;

CREATE OR REPLACE STREAM RAW.STM_RAW_ORDERS ON TABLE RAW.ORDERS;
CREATE OR REPLACE STREAM RAW.STM_RAW_LINEITEM ON TABLE RAW.LINEITEM;
CREATE OR REPLACE STREAM RAW.STM_RAW_CUSTOMERS ON TABLE RAW.CUSTOMER;

USE SCHEMA PRACTICA_FINAL_NUEVA.STAGING;

CREATE OR REPLACE STREAM STAGING.STM_STG_ORDERS ON TABLE STAGING.STG_ORDERS;
CREATE OR REPLACE STREAM STAGING.STM_STG_LINEITEM ON TABLE STAGING.STG_LINEITEM;
CREATE OR REPLACE STREAM STAGING.STM_STG_CUSTOMERS ON TABLE STAGING.STG_CUSTOMER;